version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app      # 1. Mount the entire frontend folder
      - /app/node_modules    # 2. Add an "anonymous volume" to ignore local node_modules
